# Generated by Django 3.2 on 2021-04-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='articles',
        ),
    ]
